// Use of this source code is governed by a BSD-style license.

package org.levarac.barnard

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Test

/**
 * Cross-language acceptance test for `tools/venue-envelope-producer` (the Swift CLI that
 * produces the first real signed B005 v2 venue envelope): loads the container the Swift
 * producer emitted -- real fields, a real secp256k1 signature via
 * `BarnardCoreSigning.signRecoverable`, not a hand-written vector -- from
 * `test-vectors/venue-envelope-producer-fixture.txt` and asserts this Kotlin core accepts the
 * exact same bytes.
 *
 * The fixture is generated by
 * `VenueEnvelopeProducerTests.testWriteCrossLanguageFixture` on the Swift side (in
 * `tools/venue-envelope-producer/Tests/VenueEnvelopeProducerKitTests`) and committed here, the
 * same "one side writes, the other reads" shape `BarnardOwnerKeyConformanceVectorTest` already
 * uses for `test-vectors/owner-key-v1.txt`.
 */
class BarnardVenueEnvelopeProducerFixtureTest {

    private val vectors: Map<String, String> by lazy {
        parseVectors(File(findRepoRoot(), "test-vectors/venue-envelope-producer-fixture.txt"))
    }

    private fun v(key: String): String = vectors[key] ?: error("missing vector key: $key")

    private fun hex(value: String): ByteArray {
        require(value.length % 2 == 0) { "odd-length hex value: $value" }
        return ByteArray(value.length / 2) { i -> value.substring(i * 2, i * 2 + 2).toInt(16).toByte() }
    }

    /** Same bounded upward walk `BarnardOwnerKeyConformanceVectorTest.findRepoRoot` uses. */
    private fun findRepoRoot(): File {
        var dir: File? = File(System.getProperty("user.dir")).absoluteFile
        var levels = 0
        while (dir != null && levels < 20) {
            if (File(dir, "test-vectors/venue-envelope-producer-fixture.txt").isFile) return dir
            dir = dir.parentFile
            levels++
        }
        org.junit.Assert.fail(
            "Could not locate repo root containing test-vectors/venue-envelope-producer-fixture.txt " +
                "by walking up from ${System.getProperty("user.dir")} (searched $levels levels)",
        )
        error("unreachable")
    }

    private fun parseVectors(file: File): Map<String, String> {
        val keyPattern = Regex("[A-Za-z0-9_]+")
        val result = LinkedHashMap<String, String>()
        for (line in file.readLines(Charsets.UTF_8)) {
            if (line.isEmpty() || line.startsWith("#")) continue
            val eq = line.indexOf('=')
            require(eq > 0) { "malformed vector line (no '=' or empty key): $line" }
            val key = line.substring(0, eq)
            require(keyPattern.matches(key)) { "malformed vector key: $key" }
            result[key] = line.substring(eq + 1)
        }
        return result
    }

    @Test
    fun kotlinVerifierAcceptsTheSwiftProducedContainer() {
        val container = hex(v("container_hex"))
        val currentEnin = v("current_enin").toLong()
        val verified = BarnardB005EnvelopeV2.verify(container, currentEnin)
        assertNotNull("Kotlin verify() rejected the Swift-produced container", verified)
        assertEquals(BarnardB005ReceiverState.RADIO_SELF_VERIFIED, verified!!.receiverState)
        assertEquals("Venue Test Event", verified.eventDisplayName)
    }

    @Test
    fun kotlinVerifierRejectsTheSameContainerWithAFlippedSignatureByte() {
        val container = hex(v("container_hex"))
        val currentEnin = v("current_enin").toLong()
        container[container.size - 1] = (container[container.size - 1].toInt() xor 1).toByte()
        assertEquals(null, BarnardB005EnvelopeV2.verify(container, currentEnin))
    }
}
